### ISSUE TITLE
comment the codes 

### ISSUE THREAD

**Issue by ChathuminaVimukthi** [ChathuminaVimukthi/PP02-CW-Java-OO-principles#1]

**Comment by rajedan** [comment]
I want to contribute on this project.
Can you elaborate the issue in details? Which codes you want to get commented in which files?

Appreciate.

**Comment by ChathuminaVimukthi** [comment]
You can choose any java file in "HotelArray/src" folder and comment the file.. No need too much comments but comments that describe the specific methods..This is for the ones who need to complete the hacktoberfest challenge.

Good Luck!

**Comment by rajedan** [comment]
Thanks working on it.
